site_name: Cadastro Único
site_url: https://requisitos-de-software.github.io/2025.1-Cadastro-Unico/

markdown_extensions:
  - tables
  - md_in_html

nav:
  - Home:
      - Sobre: index.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma Planejado: planejamento/cronograma.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Metodologia: planejamento/metodologia.md
    - Termos de Uso: planejamento/termosDeUso.md
  - Pré-rastreabilidade:
    - Aplicativo: pre-rastreabilidade/aplicativo.md
    - Aplicativos Analisados: pre-rastreabilidade/appsAnalisados.md
  - Elicitação:
    - Perfil de Usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Requisitos Elicitados: elicitacao/requisitos_elicitados.md
    - Técnicas de Elicitação: 
      - Introdução: elicitacao/tecnicas/introducao.md
      - Instrospecção: elicitacao/tecnicas/introspecção.md
      - Questionário: elicitacao/tecnicas/questionario.md
      - Entrevista: elicitacao/tecnicas/entrevista.md
      - Análise de Documentação: elicitacao/tecnicas/analise_documentacao.md
    - Técnicas de Priorização:
      - Introdução: elicitacao/priorizacao/introducao.md
      - $100: elicitacao/priorizacao/100dollars.md
      - MoSCoW: elicitacao/priorizacao/moscow.md
      - First Things First: elicitacao/priorizacao/first_thing_first.md
      - Three Level Scale: elicitacao/priorizacao/three_level_scale.md
  - Modelagem:
    - Introdução: modelagem/introducao.md
    - Cenários: modelagem/cenarios.md
    - Casos de Uso: modelagem/caso_de_uso.md
    - Léxicos: modelagem/lexico.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
    - Agil:
      - Historia de Usuário: modelagem/agil/historia_de_usuario.md
      - Backlog: modelagem/agil/backlog.md
      - NFR Framework: modelagem/agil/NFR.md 
  - Rastreabilidade:
    - Matriz Geral: rastreabilidade/matriz_geral.md
    - Pós-Rastreabilidade: rastreabilidade/pos-rastreabilidade.md
  - Verificação:
    - Entrega 1: verificacao/checklist_1.md
    - Entrega 2: verificacao/checklist_2.md
    - Entrega 3: verificacao/checklist_3.md
    - Entrega 4: verificacao/checklist_4.md
    - Entrega 6: verificacao/checklist_6.md
  - Validação:
    - Prototipação: prototipo/prototipo.md
    - Prototipo - João Pedro: prototipo/prototipo_JP.md
  - Inspeções:
    - Grupo:
      - Entrega 1: inspecoes/grupo/inspecao_1.md
      - Entrega 2: inspecoes/grupo/inspecao_2.md
      - Entrega 3: inspecoes/grupo/inspecao_3.md
      - Entrega 4: inspecoes/grupo/inspecao_4.md
      - Entrega 6: inspecoes/grupo/inspecao_6.md
    - Grupo+1:
      - Entrega 1: inspecoes/grupo+1/inspecao_1.md
      - Entrega 2: inspecoes/grupo+1/inspecao_2.md
      - Entrega 3: inspecoes/grupo+1/inspecao_3.md
      - Entrega 4: inspecoes/grupo+1/inspecao_4.md
      - Entrega 5: inspecoes/grupo+1/inspecao_5.md      
      - Entrega 6: inspecoes/grupo+1/inspecao_6.md
    - Inspeções Fagan:
      - Etapa 1: inspecoes/inspecao_de_fagan/etapa1.md
      - Etapa 2: inspecoes/inspecao_de_fagan/etapa2.md
      - Etapa 3: inspecoes/inspecao_de_fagan/etapa3.md
      - Etapa 4: inspecoes/inspecao_de_fagan/etapa4.md
      - Etapa 6: inspecoes/inspecao_de_fagan/etapa6.md
  - Atas de Reunião:
    - Ata 1: atas/reuniao1.md
    - Ata 2: atas/reuniao2.md
    - Ata 3: atas/reuniao3.md
    - Ata 4: atas/reuniao4.md
    - Ata 5: atas/reuniao5.md
    - Reuniões de Elicitação:
      - Reunião 1: atas/tecnicas/reuniaoElicitacao1.md
      - Reunião 2: atas/tecnicas/reuniaoElicitacao2.md
  - Apresentações:
    - Apresentação I: apresentacoes/apresentacao1.md
    - Apresentação II: apresentacoes/apresentacao2.md
    - Apresentação III: apresentacoes/apresentacao3.md
    - Apresentação IV: apresentacoes/apresentacao4.md
    - Apresentação V: apresentacoes/apresentacao5.md
    - Apresentação VI: apresentacoes/apresentacao6.md
theme:
  logo: assets/LogoCadUn.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt

extra_css:
  - assets/css/custom.css
